version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/go/src/app
      - db-data:/go/src/app/build
    working_dir: /go/src/app
    command: air
    ports:
      - 9999:9999
volumes:
  db-data:
